active_plugins:
    - display-environment-type/display-environment-type.php
    - health-check/health-check.php
    - litespeed-cache/litespeed-cache.php
    - sg-security/sg-security.php
    - wp-cfm/wp-cfm.php
.label: 'Active Plugins'
.active_plugins_format: serialized
